AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - vendor/ruby/**/*
Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
