default: &default
  host:
    url: <%= ENV['HOST_URL'] %>
    host: <%= URI.parse(ENV['HOST_URL']).host %>
    port: <%= URI.parse(ENV['HOST_URL']).port %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
