default: &default
  app:
    secret_key: <%= ENV['SECRET_KEY'] %>
    pepper: <%= ENV['PEPPER'] %>
    url: <%= uri = URI.parse(ENV['HOST_URL']); uri.path = ''; uri %>
    host: <%= URI.parse(ENV['HOST_URL']).host %>
    port: <%= URI.parse(ENV['HOST_URL']).port %>
  mailer:
    default_sender: <%= ENV['MAILER_DEFAULT_SENDER'] %>
  aws_s3:
    access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
    region: <%= ENV['AWS_S3_REGION'] %>
    bucket: <%= ENV['AWS_S3_BUCKET'] %>
    asset_host: <%= ENV['AWS_S3_ASSET_HOST'] %>
  facebook:
    app_id: <%= ENV['FB_APP_ID'] %>
    app_secret: <%= ENV['FB_APP_SECRET'] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
