# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2907f40d7ca286659b90f9b6c7097bcf51ecb8c14599eadd261489a727b38b0d32462d207a60013e13c4b193c6f1f8633cb89583632bfd0df4fc658b44fc1ae

test:
  secret_key_base: 7094bbe2e0caad5da023383f31f53eab8a40f0a5f69ac57764f4be1cd44aef4f76db68ceda2436de65ebbc26725ed34bced363c2d60a36d1c16d5973752fcb5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
